### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dominiquini** [Sopel97/railway_signalling_overseer#2]
The game crashed when I tried to delete and rebuild a rail:

-----
 652.903 Error MainLoop.cpp:1284: Exception at tick 130728090: The mod Railway Signalling Overseer (1.1.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event railway_signalling_overseer::on_tick (ID 0)
'target': table expected, got nil
stack traceback:
	[C]: in function 'draw_text'
	__railway_signalling_overseer__/control.lua:1600: in function 'update'
	__railway_signalling_overseer__/control.lua:1651: in function <__railway_signalling_overseer__/control.lua:1645>

-----

Thanks.

**Comment by Sopel97** [comment]
Thanks for the report. Should be fixed in 1.1.10.
