### ISSUE TITLE
Error while using cut tool

### ISSUE THREAD

**Issue by Solarwuff** [Sopel97/railway_signalling_overseer#3]
I got the following error while using cut tool on ghosted and normal entities 

PS i did test with ghosted and normal (industrial revolution electric miner) and belts 
![ELJ1Uy2](https://user-images.githubusercontent.com/49283198/175455434-0fe47e81-08fb-453d-b48e-297f5da0702e.png)

**Comment by Sopel97** [comment]
"Fixed" in 1.1.16. Related to https://forums.factorio.com/88100.
