### ISSUE TITLE
Non-recoverable error with 1.1.18

### ISSUE THREAD

**Issue by mdfairch** [Sopel97/railway_signalling_overseer#4]
With K2, SE, and LTN.

Screenshot of the error message:
https://mega.nz/file/3gRDmAgT#fGW4YftcGz07MLcJScM8uqVYTEgCgqYGK52VLbEUoNo

The save:
https://mega.nz/file/qsBAmTyR#pHaGDD4ZllRasbdAaDSgt6kRewihCDgZVkELNPh-Nrg

**Comment by Sopel97** [comment]
Thanks. Should be fixed in 1.1.19
