### ISSUE TITLE
Selection Tool needs deepwater-green

### ISSUE THREAD

**Issue by Neko14789** [Sopel97/railway_signalling_overseer#6]
Error ModManager.cpp:1558: Error in assignID: tile with name 'deepwater-green' does not exist. It was removed by alien-biomes.

Source: railway_signalling_overseer_assume_correct_tool (selection-tool).

**Comment by Sopel97** [comment]
Thanks for the report, should be fixed in 1.1.26

**Comment by deadspidervenom** [comment]
Current Version this issue is back.

**Comment by deadspidervenom** [comment]
After testing, it occurs when you have "remove obsolete tiles" enabled in alien biomes.

**Comment by Sopel97** [comment]
that's not possible since the line that was producing the error is no longer present

**Comment by deadspidervenom** [comment]
dont know what to say, try enabling the option. my game forced me to disable this mod for this error.

**Comment by deadspidervenom** [comment]
and yes i'm on the latest version 1.1.26

**Comment by Sopel97** [comment]
the error must be different

**Comment by deadspidervenom** [comment]
Image of me having the option enabled
![image](https://github.com/user-attachments/assets/9d728dea-a824-413d-abc4-dbfe981a0b94)
Image of me about to enable the mod with 
![image](https://github.com/user-attachments/assets/3e746c14-1d4a-416f-b473-268b5bb1a6cd)
the error occuring on mod load
![image](https://github.com/user-attachments/assets/6313f6c7-f0c9-4323-85bb-8f23ac1258cb)

**Comment by deadspidervenom** [comment]
its the same error

**Comment by Sopel97** [comment]
Alright, I see what's wrong. The file was still present in the factorio modpage distribution because I didn't delete it when updating the archive. Sorry for this mistake. 1.1.27 has the file removed and the error should be fixed.
