### ISSUE TITLE
Crash when removing rail or chain signals.

### ISSUE THREAD

**Issue by manosteele117** [Sopel97/railway_signalling_overseer#7]
With only this mod and editor extensions enabled, when removing a rail signal or chain signal, I encounter a crash. I was able to replicate this by pasting an intersection, adding one outbound rail signal, and then removing it. The crash only occurs when I have 'Show Assumptions' and Auto Updates enabled. I retested several times with the same setup using different mod settings until I narrowed it down to that option

Here is an image of the state of the game at the time of the error:
![image](https://github.com/user-attachments/assets/d6d9bc99-cb87-426b-83d2-1ce048ee9563)

Here is the save I used, including the only blueprints used in the world. The reproduce should just be to open the world, change overseer mod settings to enable Show Assumptions, and then to remove any rail signal.
[rail_overseer_bug.zip](https://github.com/user-attachments/files/17003507/rail_overseer_bug.zip)

Error Text:
The mod Railway Signalling Overseer (1.1.27) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event railway_signalling_overseer::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__railway_signalling_overseer__/control.lua:606: in function 'is_signal_marked_correct'
	__railway_signalling_overseer__/control.lua:1704: in function 'highlight_signals_assumed_correct'
	__railway_signalling_overseer__/control.lua:1803: in function 'update'
	__railway_signalling_overseer__/control.lua:1835: in function <__railway_signalling_overseer__/control.lua:1829>

**Comment by Sopel97** [comment]
Looks like there are some stale signal references that get invalidated inbetween being listed and used.

Untested fix in 1.1.28 (https://github.com/Sopel97/railway_signalling_overseer/commit/678f07483c085875dffa2b7ebf21e660a09210a4)

**Comment by manosteele117** [comment]
It appears to be fixed in 1.1.28, or at least doesn't present using the same example.
